# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 049ea8ee6fb242da21476d85d2b037834906c9d254da57427792774e4d76a7d483889a0885ad90a51d00304eda823346a2cbb14b90c6fe42ce34ca8408d82a0f

test:
  secret_key_base: 97c77f08a1e50ebc9b8a8875e2d135bb261d7b78d3f929b57a791432b0561fcdcfbe99653a1ee7b3d08171ba6f7a35ffdf168fb4998f518b6f7df60a8f28509f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
