class RemoveAllOtherCascadeDelete < ActiveRecord::Migration
  def change
		remove_foreign_key "bookmarks", column: "post"
	  remove_foreign_key "bookmarks", column: "owner"
	  remove_foreign_key "fallacies", column: "folder"
	  remove_foreign_key "fallacyfolders", column: "parent"
	  remove_foreign_key "filter_categories", "categories"
	  remove_foreign_key "filter_categories", "filters"
	  remove_foreign_key "filters", column: "who_id"
	  remove_foreign_key "filters", "provers"
	  remove_foreign_key "follows", column: "follows"
	  remove_foreign_key "follows", column: "owner"
	  remove_foreign_key "groups", column: "owner"
	  remove_foreign_key "likes", "posts"
	  remove_foreign_key "likes", "provers"
	  remove_foreign_key "posts", column: "parent_id"
	  remove_foreign_key "posts", "provers"
	  remove_foreign_key "posts", "topics"
	  remove_foreign_key "provers", column: "cur_filter"
	  remove_foreign_key "teams", "provers"
	  remove_foreign_key "teams", "topics"
	  remove_foreign_key "topic_categories", "categories"
	  remove_foreign_key "topic_categories", "topics"
	  remove_foreign_key "topics", column: "root_id"
	  remove_foreign_key "topics", "provers"
	  remove_foreign_key "users_groups", "groups"
	  remove_foreign_key "users_groups", "provers"
		add_foreign_key "bookmarks", "posts", column: "post"
	  add_foreign_key "bookmarks", "provers", column: "owner"
	  add_foreign_key "fallacies", "fallacyfolders", column: "folder"
	  add_foreign_key "fallacyfolders", "fallacyfolders", column: "parent"
	  add_foreign_key "filter_categories", "categories"
	  add_foreign_key "filter_categories", "filters"
	  add_foreign_key "filters", "provers", column: "who_id"
	  add_foreign_key "filters", "provers"
	  add_foreign_key "follows", "provers", column: "follows"
	  add_foreign_key "follows", "provers", column: "owner"
	  add_foreign_key "groups", "provers", column: "owner"
	  add_foreign_key "likes", "posts"
	  add_foreign_key "likes", "provers"
	  add_foreign_key "posts", "posts", column: "parent_id"
	  add_foreign_key "posts", "provers"
	  add_foreign_key "posts", "topics"
	  add_foreign_key "provers", "filters", column: "cur_filter"
	  add_foreign_key "teams", "provers"
	  add_foreign_key "teams", "topics"
	  add_foreign_key "topic_categories", "categories"
	  add_foreign_key "topic_categories", "topics"
	  add_foreign_key "topics", "posts", column: "root_id"
	  add_foreign_key "topics", "provers"
	  add_foreign_key "users_groups", "groups"
	  add_foreign_key "users_groups", "provers"
  end
end
